export const GET_DATE = "GET_DATE";
export const CHANGE_DATE = "CHANGE_DATE";

export const ADD_BREAKFAST = "ADD_BREAKFAST";
export const DEL_BREAKFAST = "DEL_BREAKFAST";
export const GET_BREAKFAST = "GET_BREAKFAST";
export const GET_BREAKFAST_EMPTY = "GET_BREAKFAST_EMPTY";
export const SAVE_BREAKFAST = "SAVE_BREAKFAST";